import { SharepointUser } from "../SharepointUser";

// Generated by https://quicktype.io

export interface ccRequestTracker {
  __metadata: Metadata;
  FirstUniqueAncestorSecurableObject: AttachmentFiles;
  RoleAssignments: AttachmentFiles;
  AttachmentFiles: AttachmentFiles;
  ContentType: AttachmentFiles;
  FieldValuesAsHtml: AttachmentFiles;
  FieldValuesAsText: AttachmentFiles;
  FieldValuesForEdit: AttachmentFiles;
  File: AttachmentFiles;
  Folder: AttachmentFiles;
  ParentList: AttachmentFiles;
  FileSystemObjectType: number;
  ContentTypeId: string;
  ID: number;
  Modified: string;
  Created: string;
  AuthorId: number;
  EditorId: number;
  OData__UIVersionString: string;
  Attachments: boolean;
  GUID: string;
  Id: number;
  Title: string;
  REQUEST_FIELD: string;
  PURCHASE_DETAILS: string;
  BUDGET_OFFICER_APPROVAL: string;
  BILLING_OFFICIAL_APPROVAL: string;
  J6_APPROVAL: string;
  PBO_APPROVAL: string;
  DIRECTORATE_APPROVAL: string;
  J8_APPROVAL: string;
  CARD_HOLDER_VALIDATION: string;
  REQUESTOR_VALIDATION: string;
  SUPPLY_VALIDATION: string;
  FINAL_VALIDATION: string;
  REQUEST_STATUS: string;
  Author: SharepointUser;
  History: string;
}

export interface AttachmentFiles {
  __deferred: Deferred;
}

export interface Deferred {
  uri: string;
}

export interface Metadata {
  id: string;
  uri: string;
  etag: string;
  type: string;
}
