// Generated by https://quicktype.io

export interface ICardholderValidation {
  cardHolderComment: string;
  cardHolderTransactionId: string;
  cardHolderExecuted: string;
  cardHolderSignature: string;
}
