// Generated by https://quicktype.io

export interface ILineItem {
  requestQty: number;
  requestDesc: string;
  requestSrc: string;
  requestDdForm: string;
  requestDaForm: string;
  requestCost: number;
  requestTotal: number;
}
