// Generated by https://quicktype.io

export interface IPurchaseDetails {
  Details: IDetail[];
}

interface IDetail {
  requestQty: number;
  requestDesc: string;
  requestSrc: string;
  requestDdForm: string;
  requestDaForm: string;
  requestCost: number;
  requestTotal: number;
}
