// Generated by https://quicktype.io

export interface IPurchaseDetails {
  Details: IDetail[];
}

interface IDetail {
  requestQty: string;
  requestDesc: string;
  requestSrc: string;
  requestDdForm: string;
  requestDaForm: string;
  requestCost: string;
  requestTotal: string;
}
