// Generated by https://quicktype.io

export interface IRequestField {
  RequestCardType: string;
  Requestor: string;
  RequestorCardHolderName: string;
  RequestorDSN: string;
  RequestorDirectorate: string;
  RequestDateofRequest: string;
  RequestSource: string;
  RequestJustification: string;
  RequestCurrencyType: string;
  RequestIsJ6: string;
}
