import { autoserialize } from "cerialize";

// Generated by https://quicktype.io

export class BillingOfficialApproval {
  @autoserialize
  boComment?: string;
  @autoserialize
  boStatus?: string;
  @autoserialize
  boSignature?: string;
}
