import { autoserialize } from "cerialize";

// Generated by https://quicktype.io

export class BudgetOfficerApproval {
  @autoserialize
  budgetOfficerComment?: string;
  @autoserialize
  budgetOfficerSignature?: string;
}
