import { autoserialize } from "cerialize";

// Generated by https://quicktype.io

export class CardholderValidation {
  @autoserialize
  cardHolderComment?: string;
  @autoserialize
  cardHolderTransactionId?: string;
  @autoserialize
  cardHolderExecuted?: string;
  @autoserialize
  cardHolderSignature?: string;
}
