// Generated by https://quicktype.io

export interface CurrentSharepointUser {
  Id: number;
  IsHiddenInUI: boolean;
  LoginName: string;
  Title: string;
  PrincipalType: number;
  Email: string;
  IsSiteAdmin: boolean;
}
