import { autoserialize } from "cerialize";

// Generated by https://quicktype.io

export class DirectorateApproval {
  @autoserialize
  directorateComment?: string;
  @autoserialize
  directorateStatus?: string;
  @autoserialize
  directorateSignature?: string;
}
