import { autoserialize } from "cerialize";

// Generated by https://quicktype.io

export class J6Approval {
  @autoserialize
  j6Comment?: string;
  @autoserialize
  j6Status?: string;
  @autoserialize
  j6Signature?: string;
}
