import { autoserialize } from "cerialize";

// Generated by https://quicktype.io

export class J8Approval {
  @autoserialize
  j8Comment?: string;
  @autoserialize
  j8FiscalYear?: string;
  @autoserialize
  j8Quater?: string;
  @autoserialize
  j8Signature?: string;
}
