import { autoserialize } from "cerialize";

// Generated by https://quicktype.io

export class PboApproval {
  @autoserialize
  pboComment?: string;
  @autoserialize
  pboStatus?: string;
  @autoserialize
  pboSignature?: string;
}
