import { autoserialize, autoserializeAs } from "cerialize";

// Generated by https://quicktype.io

export class Detail {
  @autoserialize
  requestQty?: string;
  @autoserialize
  requestDesc?: string;
  @autoserialize
  requestSrc?: string;
  @autoserialize
  requestDdForm?: boolean;
  @autoserialize
  requestDaForm?: boolean;
  @autoserialize
  requestCost?: string;
  @autoserialize
  requestTotal?: string;
}

export class PurchaseDetails {
  @autoserializeAs(Detail)
  Details?: Detail[];
}
