import { autoserialize } from "cerialize";

// Generated by https://quicktype.io

export class RequestorValidation {
  @autoserialize
  requestorComment?: string;
  @autoserialize
  requestorSignature?: string;
}
