import { autoserializeAs, autoserialize } from "cerialize";

// Generated by https://quicktype.io

export class Metadata {
  @autoserialize
  id?: string;

  @autoserialize
  uri?: string;

  @autoserialize
  etag?: string;
}

export class SharepointUser {
  @autoserializeAs(Metadata)
  __metadata?: Metadata;

  @autoserialize
  Id?: number;

  @autoserialize
  Title?: string;

  @autoserialize
  EMail?: null | string;

  @autoserialize
  ID?: number;

  @autoserialize
  Name?: string;

  @autoserialize
  UserName?: string;

  @autoserialize
  FirstName?: string;

  @autoserialize
  LastName?: string;
}
