import { autoserialize } from "cerialize";

// Generated by https://quicktype.io

export class SupplyValidation {
  @autoserialize
  supplyComment?: string;
  @autoserialize
  supplySignature?: string;
}
